### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by Larrey** [david-shrk/ecgaxistrainer#1]
Hi!!! My name es Al and I am a Spanish Emergency Doctor. I think your app is really interesting. Thanks a lot for it!! If you consider it is worthy, I would love to translate it to Spanish. Best Regards!!

**Comment by david-shrk** [comment]
Hi, that is a great idea, we can definitely do that. Do you know how Git works? I created a branch called 'Spanish-Version' and invited you. You could update the language.js to include the spanish text and I will do the remaining coding. Remember to include yourself in the about section as translator for the spanish version.
If you are not familiar with Git, Github oder coding in general let me know and I will walk you through it. It's quite easy.

Which system of axis types do you use in Spain? Only three to four types (normal, left axis deviation, right axis deviation, northwest-typ / extreme axis deviation) comparable to the english system?

Have a nice weekend. :)

**Comment by Larrey** [comment]
Dear David,

Thanks for your response

I already updated the Spanish language versión. I hope I did it correctly. In Spain we have the 4 types of axis model:

Normal = Normal
Left = Eje IZQUIERDO
Right = Eje DERECHO
NorthWest = EXTREMO

Best regards,


Al



Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: David ***@***.***>
Enviado: viernes, 29 de abril de 2022 18:54
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [david-shrk/ecgaxistrainer] Spanish version (Issue #1)


Hi, that is a great idea, we can definitely do that. Do you know how Git works? I created a branch called 'Spanish-Version' and invited you. You could update the language.js to include the spanish text and I will do the remaining coding. Remember to include yourself in the about section as translator for the spanish version.
If you are not familiar with Git, Github oder coding in general let me know and I will walk you through it. It's quite easy.

Which system of axis types do you use in Spain? Only three to four types (normal, left axis deviation, right axis deviation, northwest-typ / extreme axis deviation) comparable to the english system?

Have a nice weekend. :)

**Comment by david-shrk** [comment]
Hi, that looks great! :) 
I will include the necessary code to switch to spanish as soon as possible. 

I would really like to give you credit as the translator in the about-section. Do you use twitter? I could put a link to your twitter-account in there if you want to.

Best regards, 

David

**Comment by david-shrk** [comment]
Hi Al,

I added the spanish version and released it. Thank you very much for the translation. I had to inlcude very minor changes because some words/phrases were too long. 

I included a (probably poorly translated ;) ) line to at least give you credit with your first name. If you have a twitter-account or something similiar I will happily link to it in the about section.
I will leave this issue open for some days in case you want to answer here. You can also contact me on twitter.


Best regards,

David

**Comment by Larrey** [comment]
Dear David:

  *   Thanks a lot  for your effort. Its great to have it in Spanish¡¡
  *   I will replace this: (in fact, this sentene is incorrect in Spanih): "espero que pueda resultar útil para entender a calcular e interpretar el eje cardíaco"  with  "espero que pueda ser útil para aprender a interpretar y calcular el eje cardíaco".
  *   My name is Álvaro Pemartin and my Twitte account is @PemartinA
  *

Best regards,

Al

________________________________
De: David Schaack ***@***.***>
Enviado: sábado, 7 de mayo de 2022 11:24
Para: david-shrk/ecgaxistrainer ***@***.***>
Cc: Larrey ***@***.***>; Author ***@***.***>
Asunto: Re: [david-shrk/ecgaxistrainer] Spanish version (Issue #1)


Hi Al,

I added the spanish version and released it. Thank you very much for the translation. I had to inlcude very minor changes because some words/phrases were too long. And I included a (probably poorly translated ;) ) line to at least give you credit with your first name. If you have a twitter-account or something similiar I will happily link to it in the about section.

Best regards,

David
